### ISSUE TITLE
Not updating that often

### ISSUE THREAD

**Issue by Terkelchr** [ad-ha/mg-saic-ha#10]
Hello I have the standard 7200 seconds and 600 s when charging, so I would expect new data ever 2 hours? but it seems more like every 2 day instead?
I see all the 38 entities, but what about the start charging, start aircon, is this in a future setup or am I just not good enough in the HA world (im only a novice)

Sensorer
Added Electric Range
0 km
Battery Voltage
12,5 V
Bonnet Status
Lukket
Boot Status
Lukket
Brand
MG
Charging Current
0 A
Charging Duration
0
Charging Gun State
Tilsluttet strøm
Charging Status
Charging Finished
Charging Voltage
0 V
Door Front Left
Lukket
Door Front Right
Lukket
Door Rear Left
Lukket
Door Rear Right
Lukket
Electric Range
284,0 km
Estimated Range After Charging
301,0 km
Exterior Temperature
11,0 °C
HVAC Status
Kører ikke
Interior Temperature
11,0 °C
Lock Status
Låst
Mileage
17.141,0 km
Mileage Since Last Charge
0,0 km
Model
Marvel R Electric
Model Year
2021
Power Usage Since Last Charge
0,0 kWh
Remaining Charging Time
0
State of Charge
76,0%
Sun Roof Status
Lukket
Target SOC
80%
Tyre Pressure Front Left
2,76 bar
Tyre Pressure Front Right
2,76 bar
Tyre Pressure Rear Left
2,76 bar
Tyre Pressure Rear Right
2,8 bar
Window Front Left
Lukket
Window Front Right
Lukket
Window Rear Left
Lukket
Window Rear Right
Lukket
![image](https://github.com/user-attachments/assets/e42edc96-07ec-4527-a18d-fa1777ba91f5)

**Comment by Terkelchr** [comment]
It is looking nice the work you have done so fare, I also have an Marvel like you

**Comment by ad-ha** [comment]
Hi,

Thanks for the feedback. I think this is solved with release 0.3.0 >> https://github.com/ad-ha/mg-saic-ha/releases/tag/0.3.0

Let me know if it improves

**Comment by Terkelchr** [comment]
I will do that, thxTerkel Christiansen Mob 53 61 88 71 Fra: Alvaro Duarte ***@***.***>Sendt: mandag, oktober 21, 2024 12:46:24 PMTil: ad-ha/mg-saic-ha ***@***.***>Cc: Terkelchr ***@***.***>; Author ***@***.***>Emne: Re: [ad-ha/mg-saic-ha] Not updating that often (Issue #10)
Hi,
Thanks for the feedback. I think this is solved with release 0.3.0 >> https://github.com/ad-ha/mg-saic-ha/releases/tag/0.3.0
Let me know if it improves
