### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by puneethp7h** [ad-ha/mg-saic-ha#12]
Hello,

I am using mg ismart to connect to MG hector petrol suv. 
But it keeps throwing the following error:

"Failed to authenticate, please check your credentials."

I am sure the username/credentials are fine, because I am able to login to my mobile app.

Please help.

**Comment by ad-ha** [comment]
Hi,

Do you have special characters on your password? If that's the case, you need to change it on the iSmart app, as the API does not allow special characters.

**Comment by puneethp7h** [comment]
Hi, I am not able to set a password without special character in ismart. It says atleast one special character is a must.

**Comment by ad-ha** [comment]
That's quite odd. Some time ago I could change the password and do not use special characters.

I'm sorry, but I cannot help on that right now. I was checking again and the API does not accept symbols. Let me see if I mind a workaround, but does not seem something easy.

**Comment by puneethp7h** [comment]
Sure thank you 👍

**Comment by ad-ha** [comment]
I will close this as it is not an actual issue from the integration, but a bug from the API.

Cheers
