### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Johndowne** [ad-ha/mg-saic-ha#13]
Hello, thank you for this integration.
I am trying to set it up in Europe on an MG Cyberster but I get this in the logs….
Logger: custom_components.mg_saic
Source: custom_components/mg_saic/__init__.py:45
integration: MG SAIC ([documentation](https://github.com/ad-ha/mg-saic-ha), [issues](https://github.com/ad-ha/mg-saic-ha/issues))
First occurred: 08:17:29 (3 occurrences)
Last logged: 09:17:01

Failed to set up MG SAIC integration: Failed to fetch data after retries

Would you have any suggestions?

**Comment by ad-ha** [comment]
Hi,

You would need to get the debug logs activates and check full logs to understand the issue.

That seems like many generic responses from the API, which I've limit to 3 retries to avoid overload.

Once you get the debug logs, let me know.

Cheers

**Comment by Johndowne** [comment]
I see the VIN is correctly retrieved….is this what you need or do you need the detail for each event line?

Failed to set up MG SAIC integration: Failed to fetch data after retries 
 10:01:14 – (ERROR) MG SAIC (custom integration) - message first occurred at 09:52:26 and shows up 4 times
 Error fetching data: Vehicle status is None 
 10:01:13 – (ERROR) MG SAIC (custom integration) - message first occurred at 09:52:13 and shows up 12 times
 Vehicle status returned None 
 10:01:13 – (ERROR) MG SAIC (custom integration) - message first occurred at 09:52:13 and shows up 12 times
 Error retrieving vehicle status: 
 10:01:13 – (ERROR) MG SAIC (custom integration) - message first occurred at 09:52:13 and shows up 12 times
 Not retrying () 
 10:01:13 – (ERROR) MG SAIC (custom integration) - message first occurred at 09:52:13 and shows up 12 times
 Error doing job: Task exception was never retrieved (None)

**Comment by ad-ha** [comment]
So it seems that you are not getting any data from the API for the vehicle. You get the vehicle info, but not the remaining things.

For the debug logs, you need to check this: https://github.com/ad-ha/mg-saic-ha/issues/3#issuecomment-2288824987

Cheers

**Comment by Johndowne** [comment]
Here is the detail…..
This error originated from a custom integration.

Logger: saic_ismart_client_ng.api.base
Source: custom_components/mg_saic/api.py:72
integration: MG SAIC
First occurred: 09:52:13 (9 occurrences)
Last logged: 09:55:18

Not retrying ()

This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/api.py:75
integration: MG SAIC
First occurred: 09:52:13 (9 occurrences)
Last logged: 09:55:18

Error retrieving vehicle status:

This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/coordinator.py:61
integration: MG SAIC
First occurred: 09:52:13 (9 occurrences)
Last logged: 09:55:18

Vehicle status returned None

This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/coordinator.py:94
integration: MG SAIC
First occurred: 09:52:13 (9 occurrences)
Last logged: 09:55:18

Error fetching data: Vehicle status is None

This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/__init__.py:45
integration: MG SAIC
First occurred: 09:52:26 (3 occurrences)
Last logged: 09:55:19

Failed to set up MG SAIC integration: Failed to fetch data after retries

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 09:52:29 (4 occurrences)
Last logged: 09:55:20

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03'
      ^

**Comment by ad-ha** [comment]
Hi,

That's not the full log. On that page, you need to hit load full log and check for MG/SAIC.

Anyhow, based on that, the API is not sending valid data, which is not an issue from the Integration, byt MG itself.

Sometimes the API stops sending valid data, and after some hours (from a couple to 8 hours) starts working again.

**Comment by Johndowne** [comment]
Ok the problem was that the car had been locked / “sleeping” too long. As soon as  I unlocked / locked car and reloaded the integration HA populated all the details of the car status - magic!
Thanks again for this integration.
It looks like MG need to find a way to allow more than one App / device connected concurrently though.

**Comment by ad-ha** [comment]
Hi @Johndowne 

> As soon as I unlocked / locked car and reloaded the integration HA populated all the details of the car status - magic!

Good thing that it is now working.

> MG need to find a way to allow more than one App / device connected concurrently though.

I was told by MG that they are working on it. When they said so, it was a question of weeks, but already a couple of months went by, so maybe we should see it any time (not sure if it will be soon).
