### ISSUE TITLE
Battery heating switch

### ISSUE THREAD

**Issue by Johndowne** [ad-ha/mg-saic-ha#16]
Hi, would it be possible to include the battery heating switch that is available in the iSMART App? I could then make this visible in CarPlay for when I am approaching a Rapid charge point. It would make it much easier that logging onto the App etc.
Here i s screen shot of where it is in the App
![IMG_0406](https://github.com/user-attachments/assets/a9aa0d5c-5f04-4e4e-a3a5-3c978bd5fad7)

**Comment by ad-ha** [comment]
Hi @Johndowne 

Yes, there is that possibility, but my Marvel does not have that option, so I will not be able to test it. I can add a beta build to add the function, so you may try it and see if it works.

I will let you know once I am able to get it sorted.

Cheers

**Comment by Johndowne** [comment]
Great - I would be happy to try it out. I haven’t quite sorted out CarPlay actions in HA but I know it is possible and I’m sure I will work it out.

**Comment by ad-ha** [comment]
Hi @Johndowne 

Can you try this release: https://github.com/ad-ha/mg-saic-ha/releases/tag/0.4.2-b1

On HACS you need to go here: 

![image](https://github.com/user-attachments/assets/648d6b13-6f8c-4e0d-8b0e-84e4cf38b55d)


![image](https://github.com/user-attachments/assets/0e9925c1-4d38-498e-a085-3899b4d3837c)


Restart HA and check if the switch and services do work. I am not sure about the output as the API is not very well documented on the responses, but it should work.

Let me know. And after if you have the logs, that will be helpful ;)

**Comment by Johndowne** [comment]
Thanks - I will be back at home on Wednesday and will test then

**Comment by Johndowne** [comment]
I think the weather / car is too warm at the moment to test this. When I turn it in in the std App it soon turns off again with the message “Battery pack does not need to be heated”.
The switch also just resets to OFF in the Beta HA integration - but I am suspicious it has a knock on effect on the Integration as at some point after trying it out I need to “Reload” the integration to get it operational again. I’ve only experienced this  after trying the Integration Battery heating switch.
I think I need colder weather!

**Comment by Johndowne** [comment]
I realise this Enhancement is "closed" but you said you would like to see logs.
I m not very familiar with dealing with the logs so would you be able to point me to a simple guide of what you would like?

**Comment by Johndowne** [comment]
Hopefully this is right….i am on 0.4.2 now
[MG INTEGRATION.txt](https://github.com/user-attachments/files/17680911/MG.INTEGRATION.txt)

**Comment by ad-ha** [comment]
Thanks for the log @Johndowne 

Looking into it, at first glance, this is the "fun" bit of the MG API, this status, for example, `bmsPTCHeatReqDspCmd` should be 0 or 1, and in your log it has a 2.

Anyhow, it all looks fine to me. 

Whenever you can, try to activate the battery heating and send me the logs with those actions, to see the response after activating and after the reschedule update.

Thanks
