### ISSUE TITLE
Electric Range and State of Charge report unrealistic values

### ISSUE THREAD

**Issue by zorak1103** [ad-ha/mg-saic-ha#28]
Sometimes Electric Range and State of Charge report unrealistic values.

Either SoC of 102% and 0% is unrealistic, as is Electric Range of 2046 km or 0 km.

Maybe it would be possible to define cutoff values or a valid range for the integration. 

![SoC](https://github.com/user-attachments/assets/8e3f840b-25a5-4881-9655-6e8b5952baf0)
![electric range](https://github.com/user-attachments/assets/f1cedd7f-282b-4075-a90e-45a2afadc36d)

**Comment by ad-ha** [comment]
Hi

Which version of the integration are you using? On 0.4.6 this should be fixed and you should not be getting those values anymore.

**Comment by zorak1103** [comment]
This happend with 0.4.4. Just updated to 0.4.6. Will keep an eye on it.
Great work!

**Comment by ad-ha** [comment]
Great. Let me know if it works well, but for me it has been working fine and generic responses are not being parsed to the sensors.

**Comment by ad-ha** [comment]
@zorak1103 

Did the 0.4.6 fix the issue?

**Comment by zorak1103** [comment]
yes, the fix was successful. no more strange values. thanx alot!

**Comment by ad-ha** [comment]
Good to know. Thanks
