### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by leachj** [ad-ha/mg-saic-ha#35]
Thanks for creating this integration, I’m really looking forward to having home assistant integrated with my car.

When I try to setup the integration I sometimes get errors but when it is successful I get the message “no devices or entities” 

I’ve tried with both the current 0.4.7 and the alpha 0.4.8 version and I get the same result.

Any idea what might be going on here?

**Comment by leachj** [comment]
I took a look at the logs and I can see a few errors including this:

```
Logger: custom_components.mg_saic
Source: custom_components/mg_saic/coordinator.py:161
integration: MG SAIC ([documentation](https://github.com/ad-ha/mg-saic-ha), [issues](https://github.com/ad-ha/mg-saic-ha/issues))
First occurred: 20:38:25 (1 occurrences)
Last logged: 20:38:25

Failed to fetch data after 5 retries.
```

**Comment by eximo84** [comment]
Same issue, was working lovely before but now is broken which is a shame.  No doubt the MG side although the iOS App still functions.

**Comment by ad-ha** [comment]
Hi @leachj and @eximo84 

Can you guys please try on release 0.4.8 https://github.com/ad-ha/mg-saic-ha/releases/tag/0.4.8

I hope this fixes those issues.

Thanks

**Comment by leachj** [comment]
unfortunately i get the same result using 0.4.8

![Image](https://github.com/user-attachments/assets/3c8f1b64-f5d0-49d4-91d1-24b680b82db7)

**Comment by leachj** [comment]
![Image](https://github.com/user-attachments/assets/425adddc-c88c-448f-acbd-024ab1ee7ba5)

**Comment by ad-ha** [comment]
Yes, this is limited to BEV and PHEV vehicles. Is your vehicle any of those?

**Comment by ad-ha** [comment]
@leachj Do you have the full debug logs?

See here: https://github.com/ad-ha/mg-saic-ha/issues/3#issuecomment-2288824987

**Comment by ad-ha** [comment]
@leachj Can you try with version 0.5.0 and see if it works now?

**Comment by leachj** [comment]
@ad-ha yes thats fixed it, its working now. 

Can i ask what was the issue?

**Comment by ad-ha** [comment]
Great to hear that.

The issue is with the data from MG, that needs to be retry until successful data is retrieved. Now I believe this works better than before.

**Comment by eximo84** [comment]
Updated to 0.5 and i now have data but missing some sensors from before, for example i no longer have the gun state

binary_sensor.mg_eh32_x8_charging_gun_state

Also Mileage, SoC, Battery missing.... battery reporting 0% actually.

**Comment by ad-ha** [comment]
> binary_sensor.mg_eh32_x8_charging_gun_state
> 
> Also Mileage, SoC, Battery missing.... battery reporting 0% actually.

Sorry to hear that. So all those sensors come from the same status response. Did you have the logs that you may share?

Can you try to reload the integration and see if those come up?

**Comment by ad-ha** [comment]
That's weird. Did you remove the integration and added it again?

**Comment by eximo84** [comment]
I did remove it and re-add. Let me do it again.

**Comment by eximo84** [comment]
Same

```
2024-11-20 17:30:31.470 DEBUG (MainThread) [custom_components.mg_saic] Vehicle Type: HEV
```

**Comment by ad-ha** [comment]
> I did remove it and re-add. Let me do it again. 

Thanks for checking and let me know. I just saw the issue. There's a line that I've added that is not right and the vehicle type gets override by the automatic method.

I will fix it later today and do a new release.

Sorry for inconvenience. Once I do so, you just need to update and the sensors shall be back.

**Comment by eximo84** [comment]
No worries. No rush. I appreciate you even spending the time to make this integration. Just want to make it better 🙂

Thanks.

**Comment by ad-ha** [comment]
@eximo84 Released 0.5.1

I think that now your issue shall be fixed. I should just need to update, restart HA and the missing sensors should pop-up. If not, please remove and add the integration again.

Let me know if it worked.

**Comment by eximo84** [comment]
Tried. Same issue with HEV not BEV being used. Same issue with mileage and battery sensors not being available. Sorry.

```
2024-11-20 21:51:50.555 DEBUG (MainThread) [custom_components.mg_saic] Vehicle Type: HEV
2024-11-20 21:51:55.743 DEBUG (MainThread) [custom_components.mg_saic] Vehicle Type: HEV
2024-11-20 21:52:47.242 DEBUG (MainThread) [custom_components.mg_saic] Vehicle Type: HEV
2024-11-20 21:52:50.456 DEBUG (MainThread) [custom_components.mg_saic] Vehicle Type: HEV
```

**Comment by ad-ha** [comment]
> Tried. Same issue with HEV not BEV being used. Same issue with mileage and battery sensors not being available. Sorry.

Thanks @eximo84 . I assume you did try to remove and add the integration again, right?

**Comment by ad-ha** [comment]
Well, my mistake. I just saw that I've uploaded the wrong file and sent the previous version for coordinator. Meaning that I did a release with the same file for the previous release 🤦‍♂️ 

I am just trying to make some more changes to the integration, if I can get those done in the meanwhile I will update the release with it all. If not, I will just do that small change.

Sorry again for the issue and the incovenience-

**Comment by ad-ha** [comment]
@eximo84 I believe I got that fixed. Try 0.5.2

**Comment by eximo84** [comment]
Looking good 😊

**Comment by ad-ha** [comment]
Great. I believe this can now be closed, right?
