### ISSUE TITLE
[ISSUE] Battery drainage over night

### ISSUE THREAD

**Issue by zorak1103** [ad-ha/mg-saic-ha#48]
### Home Assistant Version

2024.11.3

### MG/SAIC Integration Version

0.6.1

### Installation Method

HACS

### Did you check for existing issues?

- [X] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [X] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

I don't know if this is a problem with the integration, but it looks like something is draining my battery at night. I have a loss of charge of about 1% in 11 hours. 
At night I hear the vehicle ‘clicking’ every now and then as if something is being switched on. I don't notice this behaviour when integration is deactivated. However, due to a lack of data, I cannot see whether I have lost charge.

Update interval is 7200 seconds. Charging update interval is 600 seconds.

Logging is activated. I just have to wait one night for the results.

![mg4](https://github.com/user-attachments/assets/fedda083-f9a3-482a-b5d6-d0cf748c2009)

**Comment by ad-ha** [comment]
Hi @zorak1103 

That might be related to the data update and checking the vehicle data. Sometimes, depending on the data received, the update interval might change to make sure that generic responses are discarded and valid data obtained.

Let me recheck the code for next version and see if there's something that might be looping on the updates, although I do not think it is doing something weird.

Thanks for bringing that forward.

Cheers

**Comment by x3e** [comment]
I think this is related to https://github.com/ad-ha/mg-saic-ha/issues/50 as well.

**Comment by ad-ha** [comment]
> I think this is related to https://github.com/ad-ha/mg-saic-ha/issues/50 as well.

Most probably yes, might be caused by that.

Thanks
