### ISSUE TITLE
[ISSUE] Clicking on Configuration throws an 500 Internal server error

### ISSUE THREAD

**Issue by fulesfules** [ad-ha/mg-saic-ha#55]
### Home Assistant Version

2024.13.1

### MG/SAIC Integration Version
0.71

### Installation Method

HACS

### Did you check for existing issues?

- [X] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [X] Yes, I have enabled debug logging
- [X] No, I have not enabled debug logging

### Describe the Issue

![kép](https://github.com/user-attachments/assets/6e558a12-087f-4120-8c27-88514bfdffed)
As I try to (re)configure an already configured vehicle, I got an 500 Internal server error, saying The configuration process couldn't be loaded (or something similar)

**Comment by ad-ha** [comment]
Hi @fulesfules 

Let me check. I just noticed that it also applies on my instance, although when testing before it was working fine.

I will try to get it fixed, asap.

Cheers

**Comment by dvptommy** [comment]
If you delete it and re-add it, it worked for me.

**Comment by ad-ha** [comment]
Just got it solved on 0.7.2

Check the new release with tha error fixed.

# Close

**Comment by fulesfules** [comment]
Thanks a lot, I can confirm, that it works in 0.7.2!!
