### ISSUE TITLE
[ISSUE] The size of the accumulator displayed is wrong

### ISSUE THREAD

**Issue by fulesfules** [ad-ha/mg-saic-ha#56]
### Home Assistant Version

2024.13.1

### MG/SAIC Integration Version

0.7.1

### Installation Method

HACS

### Did you check for existing issues?

- [X] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [X] Yes, I have enabled debug logging
- [X] No, I have not enabled debug logging

### Describe the Issue

![kép](https://github.com/user-attachments/assets/546c0a4f-13f6-4212-b7a5-c50f9b21901e)
The attribute showing the capacity of the accumulator is wrong. I have a standard range MG4 version with 51 kwh capacity.
https://www.fleetnews.co.uk/electric-fleet/electric-car-and-van-data/mg/mg4-1707
It displays 72.5 kwh.
It's not a big deal, rather a nice-to-have.

**Comment by ad-ha** [comment]
Hi @fulesfules 

Check the logs from the integration. That value comes directly from the response from MG, so that's an issue on MG's end, not the integration.

#Closed

**Comment by ad-ha** [comment]
@fulesfules 

Check also issue #43 with more info on this matter.
