### ISSUE TITLE
[REQ] Live update tracking

### ISSUE THREAD

**Issue by paswotz** [ad-ha/mg-saic-ha#60]
### Is your feature request related to a problem?

- [ ] Yes

### Describe the solution you'd like

Hi, is it also possible with the integration to receive live updates of identities as soon as they are changed, such as the status of doors? With another integration using MQTT, this worked without any issues.

I wanted to create a notification as soon as the doors are opened, but unfortunately, this was very delayed.

Thank you for your nice work!

**Comment by ad-ha** [comment]
Hi @paswotz

Not sure how the MQTT handles that, I would have to investigate.

Right now, the way that the API responds, that does not seem very feasible, but I will look into it.

Cheers

**Comment by ad-ha** [comment]
Hi @paswotz

Not sure how the MQTT handles that, I would have to investigate.

Right now, the way that the API responds, that does not seem very feasible, but I will look into it.

Cheers

**Comment by paswotz** [comment]
Thank you very much for your effort and hard work in fulfilling my request! I’d be really happy if this could work out soon. Donation already sent! 🚀

**Comment by ad-ha** [comment]
@paswotz ~

I've already started with the modifications, but it will not be similar to a real-time, I am adding additional intervals to check after actions, and some additional updates after vehicle powered-off, after inactive periods and long inactive periods. It is quite similar to the MQTT, but is not near "real-time".

What I'm also doing is allowing all those intervals to be set manually on the configuration, so any user may adapt to their needs.

Let me finish the development, test the workings and I will publish the release once I get everything sorted.

**Comment by ad-ha** [comment]
> Donation already sent!

Btw, appreciate the beers 🍻
