### ISSUE TITLE
[REQ] Speed and Power

### ISSUE THREAD

**Issue by jmerifjKriwe** [ad-ha/mg-saic-ha#64]
### Is your feature request related to a problem?

- [ ] Yes

### Describe the solution you'd like

If you are putting live data to ABRP the API is asking for speed and power.
So would be nice to have access to this two values as well.
Seems the SAIC HA Addon is able to deliver these two data: https://github.com/SAIC-iSmart-API/saic-java-client/blob/76e4ca8504155fc9ae75e3c847495115d87fd632/saic-java-client/src/main/java/net/heberling/ismart/abrp/ABRP.java#L23

Another - much better solution - would be an integration to deliever ABRP live data via generic token directly by this integration ;-)

**Comment by ad-ha** [comment]
Hi @jmerifjKriwe 

So, I saw those on the HA Addon and the MQTT integration, but I am not sure about the usage and the relevance about the connection with ABRP.

Would you please explain the whole thing, so I could have a better idea?

Right now I am focused on improving the integration and solving some minor things, but, by the moment, I would not discard to look into that connection with ABRP in the future.

Cheers

**Comment by jmerifjKriwe** [comment]
Well, both speed and power are not strictly necessary to use the Generic Token from ABRP. It does work without them, of course.
However, the accuracy of ABRP's evaluation and predictions becomes much more precise if you also transmit this data.
So, it’s nice to have :-)

Or are you referring to the direct integration of a data transfer to ABRP? That would simply make things easier. It can also be implemented with little effort yourself, at least if you have some knowledge. You can just follow: https://tomclaus.be/home-automation/integrating-skoda-enyaq-with-home-assistant-and-a-better-routeplanner-abrp/ (of course, adjust the sensors accordingly).

The general advantage is that you have live data in ABRP and can continuously plan during the drive without needing to install an OBD-II adapter.

A general overview of all parameters that can be transmitted to ABRP via the API can be found here: https://documenter.getpostman.com/view/7396339/SWTK5a8w.

I hope this answers your question.

**Comment by ad-ha** [comment]
Thanks @jmerifjKriwe 

Now I understand a little better the whole idea.

I been looking into the MQTT integration and seems that they pull data every 30 seconds when the vehicle is Powered On, so maybe that is just an adjustment needed on my update intervals.

I would prefer to test those intervals and see how does it go on the 12v battery end.

Anyhow, I will figure out a sensor for the speed. About power, I am not so sure what do you mean by it.

**Comment by jmerifjKriwe** [comment]
Thanks a lot for considering it :-)

Power is calculated like this: https://github.com/SAIC-iSmart-API/saic-java-client/blob/76e4ca8504155fc9ae75e3c847495115d87fd632/saic-java-client/src/main/java/net/heberling/ismart/abrp/ABRP.java#L41

I don't understand the code. Otherwise I would just create a sensor within Home Assistant and calculate by my own.

**Comment by ad-ha** [comment]
> Power is calculated like this: https://github.com/SAIC-iSmart-API/saic-java-client/blob/76e4ca8504155fc9ae75e3c847495115d87fd632/saic-java-client/src/main/java/net/heberling/ismart/abrp/ABRP.java#L41

Understood. Seams easy, although I am seeing already some conditions on the power calculation that I need to understand first.

Maybe I will not integrate with ABRP, but I may look for sure into the sensors and the update times.

**Comment by jmerifjKriwe** [comment]
Great :-)

Thanks a lot

**Comment by ad-ha** [comment]
> Great :-)
> 
> Thanks a lot

Just got those sensors sorted. The powered I already had for the charging. Just replicated it for the instant power when the vehicle is on and driving.

Let me test it tomorrow and, if all goes well, I will release the new version by then.

Cheers
