### ISSUE TITLE
Missing services

### ISSUE THREAD

**Issue by robinpersson** [ad-ha/mg-saic-ha#9]
I can´t find any services, such as Defrost Rear Window.
I can only see Sensors.

What am I missing?

Car: MG ZS EV 2021

**Comment by robinpersson** [comment]
nvm, found it

**Comment by ad-ha** [comment]
Hi,

Glad you found it and appreciate the comment. Just realized that it is not documented on the readme, so I will try to get some info added to address that.

Cheers
